## NumPy Arrays

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarr= np.array(mylist)

In [5]:
myarr

array([1, 2, 3])

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(4)

array([0.63972542, 0.62864686, 0.53293585, 0.40068017])

In [31]:
np.random.rand(4,2)

array([[0.85280806, 0.20374652],
       [0.19799604, 0.09890812],
       [0.20268919, 0.16321779],
       [0.7801675 , 0.20579515]])

In [32]:
np.random.randn(3,4)

array([[ 2.46389456, -0.14524501, -1.58544679,  0.76361734],
       [-0.86561905,  0.47977114,  0.6009026 , -0.58326947],
       [-1.09593333,  1.93071136,  0.20980104, -0.68668088]])

In [48]:
np.random.randint(2,10)

6

In [49]:
np.random.randint(2,10, size = (3,4))

array([[6, 4, 7, 8],
       [4, 6, 2, 7],
       [2, 6, 8, 4]])

In [50]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [53]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [61]:
arr = np.arange(0,16)

In [64]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
ranarr = np.random.randint(0,101,10)

In [76]:
ranarr

array([57, 21, 88, 48, 90, 58, 41, 91, 59, 79])

In [77]:
ranarr.max()

91

In [78]:
ranarr.argmax()

7

In [79]:
ranarr.min()

21

In [80]:
ranarr.argmin()

1

In [82]:
ranarr.dtype

dtype('int32')